name: cdc-notify-2

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 9 * *'

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:      
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          # For posting a simple plain text message
          slack-message: "9日になりました。あくろす抽選の確認をしましょう。 https://chofuacross-reserve.jp/ <@jishiha>"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
